---
Resources:
  MessagesDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: 'message_id'
          AttributeType: 'S'
      KeySchema:
        -
          AttributeName: 'message_id'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST
      TableName: Messages-${opt:stage, self:provider.stage}
